### ISSUE TITLE
Error after running script

### ISSUE THREAD

**Issue by ptitb** [beyondio/LittlePrinterPi#1]
I installed the script as described at https://github.com/beyondio/LittlePrinterPi/wiki/script on my RPi B.
After running the script and starting honcho I noticed it didn't show:

`web.1  | DEBUG:geventwebsocket.handler:Initializing WebSocket
web.1  | DEBUG:geventwebsocket.handler:Validating WebSocket request`

As I was supposed to see after the line:
`web.1  | DEBUG:sirius.web.webapp:Creating app.`

It started and I was able to view the Little Printer web interface but couldn't login with twitter, it gave me the `Internal Server Error`.

After checking the DEBUG messages I saw that it was missing database tables.
When I manual ran `./manage.py db upgrade` everything worked perfectly!

**Comment by anneris** [comment]
Did the script mention anything while it was running the installation?
Under the line:`'Upgrading the sirius Postsql database'`

**Comment by ptitb** [comment]
I'm not sure anymore, I believe it gave some errors. Tried looking for a logfile in var/log, but can't find the debug output. Do you know where to look, if there is any?

**Comment by anneris** [comment]
Normally the output was shown in the console, so you might not be able to recover it.
No worries, I will try to reproduce the error.

**Comment by mungle** [comment]
Hello! I'm getting the same error...
Firt I thought it was a install error, so I re-flashed the full Raspbian Jessie to be sure but I'm getting the same issue and when I try to connect to my twitter account I get an Internal Server Error... Please, HELP ME...! 😭 😆 
Thanks!

Here the error if I try to manually run `./manage.py db upgrade`

```
root@raspberrypi:/opt/sirius# ./manage.py db upgrade
Importing environment from .env...
Traceback (most recent call last):
  File "./manage.py", line 11, in <module>
    from sirius.web import web app
  File "/opt/sirius/sirius/web/webapp.py", line 7, in <module>
    import _gevent_polyfill
  File "/opt/sirius/sirius/web/_gevent_polyfill.py", line 6, in <module>
    import gevent.ssl as ssl2
ImportError: No module named gevent.ssl 
```

**Comment by mungle** [comment]
After running this command everything worked:
`pip install -r $SIRIUS_PATH/requirements.txt`
it seems that during installation on mi Pi all dependencies wasn't installed...

**Comment by anneris** [comment]
Strange, because it should do that at install with the script...
Might have to do with the $SIRIUS_PATH that is not properly initialized.

Anyway, good you have things up and running now!

**Comment by jonathanrelf** [comment]
I've tried this now on Raspbian Jessie with Python 2.7.9 and was initially getting the "ImportError: No module named gevent.ssl" exception.
Turns out I'd run the pip install via sudo which hadn't sorted out the dependencies for the pi user. So re-running this step did stop me seeing the gevent.ssl problem. 

However, running the 'db upgrade' command from within the $SIRIUS_PATH directory results in sqlalchemy error saying `sqlalchemy.exc.OperationalError: (OperationalError) unable to open database file None None`

I'm assuming that the database migrations creates the database file that's used by libpq-dev to create a working database? The .env file mentions Heroku but I'm wanting to only run locally on the Raspberry Pi. Nothing else in the script mentions about amending the environment created by mkvirtualenv.

So how does this magic work? Any tips? Many thanks

- python 2.7.9
- libpq-dev : 9.4.9-0+deb8ui
- python-pip : 1.5.6-5
- libfreetype6-dev : 2.6-2rpi1rpi1g
- fontconfig : 2.11.0-6.3+dev8u1
- libgstreamer0.10-dev : 0.10.36-1.5
- python-dev : 2.7.9-1

**Comment by jonathanrelf** [comment]
This was a permissions problem where the directory in /opt/sirius was owned by root:root but the migrations were being run by the default pi user. Found inspiration from http://stackoverflow.com/questions/18208492/sqlalchemy-exc-operationalerror-operationalerror-unable-to-open-database-file
So by running the migration through sudo as `sudo python $SIRIUS_PATH/manage.py db upgrade` worked
Decided to leave my previous comment in case others had similar problems.

**Comment by bskrt** [comment]
@jonathanrelf glad you fixed the issue & thanks for sharing!
